### ISSUE TITLE
Rhino 7

### ISSUE THREAD

**Issue by zapit** [cesarvandevelde/rhino-gears#3]
Hi,
Rhino-Gears works fine with Rhino 5 - but I don't get it to work with Rhino 7
Is it my fault or doesn't Rhino-Gears work in Rhino 7?
Regards
Seb

**Comment by cesarvandevelde** [comment]
I have not upgraded to Rhino 7 yet, so I cannot offer much help. On Rhino 6 Mac, there is a bug that causes the plugin to be placed in the wrong directory. If you're running on Mac, try the following steps:

1. Exit Rhino
2. Finder: Go > Go to folder: ~/Library/Application Support/McNeel/Rhinoceros/
3. Go into the MacPlugIns folder and copy the PythonPlugIns folder
4. Go into the folder 6.0/Plug-ins and paste
5. Restart Rhino

Unfortunately, the plugin infrastructure in Rhino is rife with problems, and McNeel has not been responsive to bug reports...

**Comment by zapit** [comment]
Hi Cesar,

I copied RhinoGears to
~/Library/Application Support/McNeel/Rhinoceros/7.0/Plug-ins/PythonPlugIns/RhinoGears\

That solves the issue with Rhino7

THX a lot for your support!
Sebastian

**Comment by ottle** [comment]
Hello zapit, I´m  from Germany

I also will use Gears in Rhino7 

What you copy into this folder? 

The complete downloaded File folder? 
![Unbenannt](https://user-images.githubusercontent.com/35903129/155664967-d7c7ed9e-4e21-422b-826a-41a5cb42d8a1.PNG)
